### ISSUE TITLE
Midnight 1.8.1 and 1.8.2 crashing on server start

### ISSUE THREAD

**Issue by crdtrd** [TelepathicGrunt/RepurposedStructures#398]
Is saying Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437. Did a tiny bit of research and I think it's trying to call client code on the server. Weird. 1.8.0 for mc1.21.9-rc1 seems to work fine on mc1.21.9 though.
Logs:
<details>
  <summary>1.8.1</summary>

  ```
  [06:48:49] [main/INFO]: Loading Minecraft 1.21.9 with Fabric Loader 0.17.2
[06:48:49] [main/INFO]: Loading 42 mods:
	- fabric-api 0.134.0+1.21.9
	   |-- fabric-api-base 1.0.0+14b92d897d
	   |-- fabric-api-lookup-api-v1 1.6.106+d17682157d
	   |-- fabric-biome-api-v1 16.1.0+c2417d4f7d
	   |-- fabric-block-api-v1 1.1.5+d17682157d
	   |-- fabric-block-view-api-v2 1.0.34+e4fd1b927d
	   |-- fabric-command-api-v2 2.3.7+328a75ba7d
	   |-- fabric-content-registries-v0 10.2.3+b6a242647d
	   |-- fabric-convention-tags-v1 2.1.47+7f945d5b7d
	   |-- fabric-convention-tags-v2 2.15.12+3154c1c87d
	   |-- fabric-crash-report-info-v1 0.3.18+33df5e6e7d
	   |-- fabric-data-attachment-api-v1 1.8.28+9bce411b7d
	   |-- fabric-data-generation-api-v1 23.2.22+d8b85ef17d
	   |-- fabric-dimensions-v1 4.0.22+38b9cc197d
	   |-- fabric-entity-events-v1 2.1.12+14b92d897d
	   |-- fabric-events-interaction-v0 4.0.35+5ba217127d
	   |-- fabric-game-rule-api-v1 1.1.1+e47eaae57d
	   |-- fabric-item-api-v1 11.5.8+9bce411b7d
	   |-- fabric-item-group-api-v1 4.2.24+86b3ae577d
	   |-- fabric-key-binding-api-v1 1.1.1+b3ba9c487d
	   |-- fabric-lifecycle-events-v1 2.6.9+33df5e6e7d
	   |-- fabric-loot-api-v2 3.0.64+3f89f5a57d
	   |-- fabric-loot-api-v3 2.0.11+d17682157d
	   |-- fabric-message-api-v1 6.1.7+3154c1c87d
	   |-- fabric-model-loading-api-v1 6.0.0+3ffd6ef07d
	   |-- fabric-networking-api-v1 5.0.13+d269470c7d
	   |-- fabric-object-builder-api-v1 21.1.24+9bce411b7d
	   |-- fabric-particles-v1 4.2.2+a0ee59a47d
	   |-- fabric-recipe-api-v1 8.1.26+d17682157d
	   |-- fabric-registry-sync-v0 6.1.41+679c8c5c7d
	   |-- fabric-renderer-api-v1 7.1.1+328a75ba7d
	   |-- fabric-renderer-indigo 4.0.19+328a75ba7d
	   |-- fabric-rendering-fluids-v1 3.1.38+86b3ae577d
	   |-- fabric-rendering-v1 16.0.1+328a75ba7d
	   |-- fabric-resource-conditions-api-v1 5.0.28+33df5e6e7d
	   |-- fabric-resource-loader-v0 3.2.2+3388a3b27d
	   |-- fabric-resource-loader-v1 1.0.2+225bca407d
	   |-- fabric-screen-api-v1 3.1.0+9c82a7987d
	   |-- fabric-screen-handler-api-v1 1.3.150+d17682157d
	   |-- fabric-serialization-api-v1 1.0.0+d857c9767d
	   |-- fabric-sound-api-v1 1.0.45+328a75ba7d
	   |-- fabric-tag-api-v1 1.2.10+2fa446b27d
	   |-- fabric-transfer-api-v1 6.0.15+79ec2c127d
	   \-- fabric-transitive-access-wideners-v1 6.5.3+41eb43437d
	- fabricloader 0.17.2
	   \-- mixinextras 0.5.0
	- java 21
	- midnightlib 1.8.1
	- minecraft 1.21.9
[06:48:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.16.3+mixin.0.8.7/sponge-mixin-0.16.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[06:48:49] [main/INFO]: Compatibility level set to JAVA_21
[06:48:50] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.5.0).
[06:48:54] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'midnightlib' at 'eu.midnightdust.fabric.core.MidnightLibFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:409) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.17.2.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:112) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.9-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
	at knot/eu.midnightdust.core.MidnightLib.registerAutoCommand(MidnightLib.java:30) ~[midnightlib-1.8.1-fabric+1.21.9.jar:?]
	at knot/eu.midnightdust.fabric.core.MidnightLibFabric.onInitializeServer(MidnightLibFabric.java:14) ~[midnightlib-1.8.1-fabric+1.21.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at knot/eu.midnightdust.core.MidnightLib.registerAutoCommand(MidnightLib.java:30) ~[midnightlib-1.8.1-fabric+1.21.9.jar:?]
	at knot/eu.midnightdust.fabric.core.MidnightLibFabric.onInitializeServer(MidnightLibFabric.java:14) ~[midnightlib-1.8.1-fabric+1.21.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
	... 7 more

  ```
</details>

<details>
  <summary>1.8.2 (basically the same as 1.8.1)</summary>

  ```
  [06:49:27] [main/INFO]: Loading Minecraft 1.21.9 with Fabric Loader 0.17.2
[06:49:27] [main/INFO]: Loading 42 mods:
	- fabric-api 0.134.0+1.21.9
	   |-- fabric-api-base 1.0.0+14b92d897d
	   |-- fabric-api-lookup-api-v1 1.6.106+d17682157d
	   |-- fabric-biome-api-v1 16.1.0+c2417d4f7d
	   |-- fabric-block-api-v1 1.1.5+d17682157d
	   |-- fabric-block-view-api-v2 1.0.34+e4fd1b927d
	   |-- fabric-command-api-v2 2.3.7+328a75ba7d
	   |-- fabric-content-registries-v0 10.2.3+b6a242647d
	   |-- fabric-convention-tags-v1 2.1.47+7f945d5b7d
	   |-- fabric-convention-tags-v2 2.15.12+3154c1c87d
	   |-- fabric-crash-report-info-v1 0.3.18+33df5e6e7d
	   |-- fabric-data-attachment-api-v1 1.8.28+9bce411b7d
	   |-- fabric-data-generation-api-v1 23.2.22+d8b85ef17d
	   |-- fabric-dimensions-v1 4.0.22+38b9cc197d
	   |-- fabric-entity-events-v1 2.1.12+14b92d897d
	   |-- fabric-events-interaction-v0 4.0.35+5ba217127d
	   |-- fabric-game-rule-api-v1 1.1.1+e47eaae57d
	   |-- fabric-item-api-v1 11.5.8+9bce411b7d
	   |-- fabric-item-group-api-v1 4.2.24+86b3ae577d
	   |-- fabric-key-binding-api-v1 1.1.1+b3ba9c487d
	   |-- fabric-lifecycle-events-v1 2.6.9+33df5e6e7d
	   |-- fabric-loot-api-v2 3.0.64+3f89f5a57d
	   |-- fabric-loot-api-v3 2.0.11+d17682157d
	   |-- fabric-message-api-v1 6.1.7+3154c1c87d
	   |-- fabric-model-loading-api-v1 6.0.0+3ffd6ef07d
	   |-- fabric-networking-api-v1 5.0.13+d269470c7d
	   |-- fabric-object-builder-api-v1 21.1.24+9bce411b7d
	   |-- fabric-particles-v1 4.2.2+a0ee59a47d
	   |-- fabric-recipe-api-v1 8.1.26+d17682157d
	   |-- fabric-registry-sync-v0 6.1.41+679c8c5c7d
	   |-- fabric-renderer-api-v1 7.1.1+328a75ba7d
	   |-- fabric-renderer-indigo 4.0.19+328a75ba7d
	   |-- fabric-rendering-fluids-v1 3.1.38+86b3ae577d
	   |-- fabric-rendering-v1 16.0.1+328a75ba7d
	   |-- fabric-resource-conditions-api-v1 5.0.28+33df5e6e7d
	   |-- fabric-resource-loader-v0 3.2.2+3388a3b27d
	   |-- fabric-resource-loader-v1 1.0.2+225bca407d
	   |-- fabric-screen-api-v1 3.1.0+9c82a7987d
	   |-- fabric-screen-handler-api-v1 1.3.150+d17682157d
	   |-- fabric-serialization-api-v1 1.0.0+d857c9767d
	   |-- fabric-sound-api-v1 1.0.45+328a75ba7d
	   |-- fabric-tag-api-v1 1.2.10+2fa446b27d
	   |-- fabric-transfer-api-v1 6.0.15+79ec2c127d
	   \-- fabric-transitive-access-wideners-v1 6.5.3+41eb43437d
	- fabricloader 0.17.2
	   \-- mixinextras 0.5.0
	- java 21
	- midnightlib 1.8.2
	- minecraft 1.21.9
[06:49:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.16.3+mixin.0.8.7/sponge-mixin-0.16.3+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[06:49:27] [main/INFO]: Compatibility level set to JAVA_21
[06:49:27] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.5.0).
[06:49:32] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'midnightlib' at 'eu.midnightdust.fabric.core.MidnightLibFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:409) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.17.2.jar:?]
	at knot/net.minecraft.server.Main.main(Main.java:112) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.17.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.9-loader.0.17.2-launcher.1.1.0.jar:1.1.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
	at knot/eu.midnightdust.core.MidnightLib.registerAutoCommand(MidnightLib.java:30) ~[midnightlib-1.8.2-fabric+1.21.9.jar:?]
	at knot/eu.midnightdust.fabric.core.MidnightLibFabric.onInitializeServer(MidnightLibFabric.java:14) ~[midnightlib-1.8.2-fabric+1.21.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239) ~[fabric-loader-0.17.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.2.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at knot/eu.midnightdust.core.MidnightLib.registerAutoCommand(MidnightLib.java:30) ~[midnightlib-1.8.2-fabric+1.21.9.jar:?]
	at knot/eu.midnightdust.fabric.core.MidnightLibFabric.onInitializeServer(MidnightLibFabric.java:14) ~[midnightlib-1.8.2-fabric+1.21.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
	... 7 more

  ```
</details>

**Comment by TelepathicGrunt** [comment]
It would help me immensely to have the entire log file please. That will state the exact lines of code calling the missing class which would allow me to know where in the mod code to look

**Comment by TelepathicGrunt** [comment]
~~Also, 1.8.1/.1.8.2 is not a versioning for repurposed structures which makes this 100% more confusing. I definitely need the log file to know what you’re seeing~~

<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/05239046-8777-4b37-baf4-e08e6c73d6b0" />

**Comment by TelepathicGrunt** [comment]
Ah update, I didn’t realize the 1.8.1/1.8.1 in your message was collapsed sections. That looks like a crash on midnightlib side. You should be making an issue report to them so they can fix it. Midnightlib is not my mod

Cc: @Motschen heads up about this

**Comment by Motschen** [comment]
This is probably the result of me needing to remove the `@EnvType` annotations due to NeoForge complaining about them. I'll make sure to fix it asap.

**Comment by Motschen** [comment]
Fixed in v1.8.3, this can be closed :)

**Comment by TelepathicGrunt** [comment]
Thank you!
